export const appConfig = {
  supabaseUrl: "https://TU_PROYECTO.supabase.co",
  supabasePublishableKey: "TU_SUPABASE_PUBLISHABLE_KEY_PUBLICA",
  supabaseAnonKey: "TU_SUPABASE_ANON_KEY_PUBLICA",
  notificationFunctionName: "send-claim-email",
  brand: {
    name: "Tu Negocio",
    logoPath: "./assets/brand-logo.svg",
    metaDescription:
      "Plantilla para una promocion con QR, registro unico y panel administrativo.",
    adminEmailPlaceholder: "admin@tunegocio.com",
  },
  campaign: {
    locale: "es-SV",
    timeZone: "America/El_Salvador",
    registrationDeadlineIso: "2026-05-16T23:59:59-06:00",
    redemptionDeadlineIso: "2026-05-31T23:59:59-06:00",
    introKicker: "Promocion exclusiva",
    introTitle: "Sorpresa",
    introCopy: "Hay un beneficio reservado para ti.",
    heroEyebrow: "Beneficio activado por QR",
    heroTitlePrefix: "Sorpresa, te has ganado",
    heroTitleHighlight: "un beneficio exclusivo",
    heroBody:
      "Valida la clave de tu QR y completa tu registro para reservar el beneficio.",
    offerTitle: "Beneficio exclusivo",
    offerDescription: "Completa tu registro para reservarlo.",
    registrationSectionTitle: "Vamos a revisar que tu codigo QR sea valido.",
    registrationClosedTitle: "Proceso de registro para canjear beneficio.",
    codeValidationTitle: "Valida tu QR",
    formSectionTitle: "Completa tus datos",
    successTitle: "Tu beneficio ya quedo reservado.",
    termsSectionTitle: "Condiciones oficiales de la promocion.",
    termsModalIntro: "Revisa las condiciones antes de confirmar tu registro.",
    footerNote: "Promocion vigente hasta la fecha de canje publicada.",
    redemptionInstructions: [
      "Presenta el documento y el correo que registraste al momento del canje.",
      "El beneficio aplica una sola vez por participante y por codigo unico.",
      "El canje queda sujeto a validacion del equipo del negocio.",
    ],
    terms: [
      "El beneficio aplica una sola vez por participante y por codigo unico.",
      "Consulta en el punto de canje cualquier restriccion adicional del beneficio.",
      "La fecha limite de registro y de canje se muestra en esta pagina.",
      "El negocio puede rechazar el canje si los datos del participante no coinciden.",
    ],
  },
  participant: {
    identifierLabel: "Documento",
    identifierPlaceholder: "ABC-123456",
    identifierPattern: "^[A-Z0-9-]{6,20}$",
    identifierNormalizationPattern: "[^A-Z0-9]",
    identifierInputMode: "text",
    whatsappLabel: "WhatsApp",
    whatsappPlaceholder: "1234-5678",
    whatsappCountryCode: "503",
    whatsappLocalPattern: "^[567][0-9]{7}$",
    whatsappFormatGroups: [4, 4],
  },
  admin: {
    title: "Panel administrativo",
    subtitle: "Consulta participantes y registra el canje de la promocion.",
    searchPlaceholder: "Ejemplo: 1234-5678 o PROMO-2026-001",
  },
  emailTemplate: {
    subject: "Tu registro fue confirmado",
    headline: "Tu registro fue confirmado",
    confirmationMessage:
      "Hola {{first_name}}, tu beneficio ya quedo registrado.",
    instructionsTitle: "Indicaciones para canjear",
    termsTitle: "Terminos y condiciones",
  },
};
