export const appConfig = {
  supabaseUrl: "https://wsrwkhjmmhpuqbencejv.supabase.co",
  supabasePublishableKey: "sb_publishable_8o8aWunSnvOX3a3cKiIspw_zBfl4HxM",
  supabaseAnonKey:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzcndraGptbWhwdXFiZW5jZWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNjY5MDEsImV4cCI6MjA5Mzg0MjkwMX0.nbds1NiwJaxgaUa19RRkVKwzqeK8ALAsj6pfbAiOQWg",
  notificationFunctionName: "send-claim-email",
  brand: {
    name: "Tempora",
    logoPath: "./assets/tempora-mark.svg",
    metaDescription:
      "Registro de beneficio y experiencia de marca de Tempora, velas decorativas artesanales.",
    adminEmailPlaceholder: "temporasv2025@gmail.com",
  },
  campaign: {
    locale: "es-SV",
    timeZone: "America/El_Salvador",
    registrationDeadlineIso: "2026-05-31T23:59:59-06:00",
    redemptionDeadlineIso: "2026-07-30T23:59:59-06:00",
    introKicker: "Velas decorativas artesanales",
    introTitle: "Tiempo de luz",
    introCopy: "Tiempo para ti.",
    heroEyebrow: "Coleccion artesanal",
    heroTitlePrefix: "Un detalle de luz",
    heroTitleHighlight: "descuento del 10% en velitas",
    heroBody:
      "Valida la clave de tu QR y completa tu registro para reservar tu beneficio exclusivo de Tempora.",
    offerTitle: "Descuento",
    offerDescription: "Descuento del 10% en la compra de velitas.",
    registrationSectionTitle: "Vamos a confirmar tu codigo para preparar tu beneficio.",
    registrationClosedTitle: "Proceso de registro para canjear beneficio.",
    codeValidationTitle: "Valida tu QR",
    formSectionTitle: "Completa tus datos",
    successTitle: "Tu beneficio Tempora ya quedo reservado.",
    termsSectionTitle: "Condiciones de tu beneficio Tempora.",
    termsModalIntro: "Revisa las condiciones antes de confirmar tu registro.",
    footerNote: "Tempora crea velas decorativas artesanales hechas con dedicacion y amor.",
    redemptionInstructions: [
      "Presenta el documento y el correo que registraste al momento del canje.",
      "El beneficio aplica una sola vez por participante y por codigo unico.",
      "El canje queda sujeto a validacion del equipo Tempora.",
    ],
    terms: [
      "El beneficio aplica una sola vez por participante y por codigo unico.",
      "Consulta en el punto de canje cualquier restriccion adicional del beneficio.",
      "La fecha limite de registro y de canje se muestra en esta pagina.",
      "Tempora puede rechazar el canje si los datos del participante no coinciden.",
    ],
  },
  participant: {
    identifierLabel: "DUI",
    identifierPlaceholder: "12345678-9",
    identifierPattern: "^[A-Z0-9-]{6,20}$",
    identifierNormalizationPattern: "[^A-Z0-9]",
    identifierInputMode: "text",
    whatsappLabel: "WhatsApp",
    whatsappPlaceholder: "1234-5678",
    whatsappCountryCode: "503",
    whatsappLocalPattern: "^[567][0-9]{7}$",
    whatsappFormatGroups: [4, 4],
  },
  admin: {
    title: "Panel Tempora",
    subtitle: "Consulta participantes y valida beneficios reservados por la marca.",
    searchPlaceholder: "Ejemplo: 1234-5678 o TEMPORA-001",
  },
  emailTemplate: {
    subject: "Tu beneficio Tempora fue confirmado",
    headline: "Tu beneficio Tempora fue confirmado",
    confirmationMessage:
      "Hola {{first_name}}, tu beneficio Tempora ya quedo registrado.",
    instructionsTitle: "Indicaciones para canjear",
    termsTitle: "Terminos y condiciones",
  },
};
